server.port: 8082

spring.kafka.producer:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
  key-serializer: org.apache.kafka.common.serialization.StringSerializer
  value-serializer: org.apache.kafka.common.serialization.StringSerializer

wikimedia:
  sse:
    host: "https://stream.wikimedia.org"
    endpoint: "/v2/stream/recentchange"
  kafka.topic: "wikimedia.recentchange"